# 2023年04月29日
### 总结

今天服务器记录了多起由于数据包过大导致的连接丢失，特别是在凌晨3点到4点之间。此外，一名玩家Cloud_ling多次登录和离开游戏，并且在下午18:44左右尝试进行一些游戏内操作，但最终因服务器问题未能成功。在19:08左右，服务器出现严重问题，导致多个玩家因StackOverflowError而掉线。在19:21左右，玩家hereiszd试图通过使用命令恢复游戏，但最终也因服务器问题而离开。在19:23，服务器重新启动，并在19:29有玩家成功登录。之后，服务器继续记录了多起连接丢失事件。

### 亮点

- **Cloud_ling的多次登录尝试**：Cloud_ling在游戏中的活跃表现，尽管频繁掉线，但多次尝试登录显示其游戏的热情。
- **hereiszd的尝试**：玩家hereiszd在遇到服务器问题时尝试恢复游戏，显示其解决问题的努力和尝试。
- **服务器重启和重新登录**：服务器在出现严重问题后成功重启，并允许玩家Cloud_ling重新登录，显示出服务器管理的有效性。
```
[03:18:43]/149.102.143.151:37826 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[03:36:31]/149.102.143.151:33134 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[03:44:39]/149.102.143.151:46322 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[03:48:31]/149.102.143.151:56724 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[03:55:17]/149.102.143.151:37270 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[04:00:48]/149.102.143.151:47272 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[04:06:27]/149.102.143.151:54550 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[04:11:11]/149.102.143.151:54430 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[04:16:21]/149.102.143.151:43168 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[04:19:48]/149.102.143.151:44428 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[04:27:48]/149.102.143.151:35858 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[07:37:47]/132.145.71.44:49730 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[09:07:57]com.mojang.authlib.GameProfile@4dc737df[id=<null>,name=Cloud_ling,properties={},legacy=false] (/120.221.106.136:47585) lost connection: Disconnected
[09:42:26]Cloud_ling[/120.221.106.136:1993] logged in with entity id 24769 at (2822.8411126398732, 64.0, 1412.292904146021)
[09:42:26]Cloud_ling joined the game
[09:43:59]Cloud_ling lost connection: Timed out
[09:43:59]Cloud_ling left the game
[09:44:22]Cloud_ling[/120.221.106.136:14563] logged in with entity id 25313 at (2815.8239895688957, 64.0, 1417.2794714105946)
[09:44:22]Cloud_ling joined the game
[09:46:30]Cloud_ling lost connection: Disconnected
[09:46:30]Cloud_ling left the game
[09:46:32]Cloud_ling[/120.221.106.136:28088] logged in with entity id 25990 at (2810.4762478221955, 64.5, 1394.3599998917118)
[09:46:32]Cloud_ling joined the game
[09:48:02]Cloud_ling lost connection: Timed out
[09:48:02]Cloud_ling left the game
[09:48:44]Cloud_ling[/120.221.106.136:42519] logged in with entity id 26532 at (2809.196197997803, 65.17675927506424, 1422.8371429180436)
[09:48:44]Cloud_ling joined the game
[09:57:26]Cloud_ling lost connection: Disconnected
[09:57:26]Cloud_ling left the game
[10:04:12]Cloud_ling[/120.221.106.136:9701] logged in with entity id 28814 at (2807.8307703752935, 65.0, 1429.3255760219813)
[10:04:12]Cloud_ling joined the game
[10:09:45]Cloud_ling lost connection: Disconnected
[10:09:45]Cloud_ling left the game
[10:09:47]Cloud_ling[/120.221.106.136:46684] logged in with entity id 31799 at (246.10053956201827, 129.0, 190.5)
[10:09:47]Cloud_ling joined the game
[10:14:34]Cloud_ling lost connection: Disconnected
[10:14:34]Cloud_ling left the game
[10:14:36]Cloud_ling[/120.221.106.136:12493] logged in with entity id 33437 at (174.02367063908966, 67.5, -146.47836061921257)
[10:14:36]Cloud_ling joined the game
[10:22:07]Cloud_ling lost connection: Disconnected
[10:22:07]Cloud_ling left the game
[10:27:50]Cloud_ling[/120.221.106.136:31087] logged in with entity id 38514 at (2805.9563748310698, 66.0, 1411.4654865170148)
[10:27:50]Cloud_ling joined the game
[10:31:23]<Cloud_ling> !!stats list
[10:31:30]<Cloud_ling> !!stats scoreboard run
[10:31:30]Saving the game (this may take a moment!)
[10:31:30]Saved the game
[10:31:30]Set [跑步榜] for Corbya to 15062142
[10:31:31]...et whc ak ioi StatsHelper 173750<--[HERE]
[10:50:23]<Cloud_ling> !!qb make
[10:50:23]Automatic saving is now disabled
[10:50:23]Saving the game (this may take a moment!)
[10:50:24]ThreadedAnvilChunkStorage (world): All chunks are saved
[10:50:24]ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[10:50:24]ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[10:50:24]Saved the game
[10:51:11]Automatic saving is now enabled
[10:58:22]Cloud_ling lost connection: Disconnected
[10:58:22]Cloud_ling left the game
[11:14:16]Cloud_ling[/120.221.106.136:17492] logged in with entity id 45679 at (2804.6541138441235, 70.0, 1411.9568059472012)
[11:14:16]Cloud_ling joined the game
[11:21:15]Cloud_ling lost connection: Disconnected
[11:21:15]Cloud_ling left the game
[11:29:54]Cloud_ling[/120.221.106.136:57524] logged in with entity id 47589 at (2803.721682538976, 71.0, 1410.70323423964)
[11:29:54]Cloud_ling joined the game
[11:38:08]Cloud_ling lost connection: Disconnected
[11:38:08]Cloud_ling left the game
[11:38:10]Cloud_ling[/120.221.106.136:46472] logged in with entity id 49930 at (2821.6107295430475, 64.0, 1374.3326507595295)
[11:38:10]Cloud_ling joined the game
[11:46:59]Cloud_ling lost connection: Disconnected
[11:46:59]Cloud_ling left the game
[12:33:13]/149.102.143.151:41820 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[12:56:22]Cloud_ling[/120.221.106.136:11556] logged in with entity id 52188 at (2796.322004013992, 67.5, 1376.5369721918014)
[12:56:22]Cloud_ling joined the game
[12:56:27]Cloud_ling lost connection: Disconnected
[12:56:27]Cloud_ling left the game
[12:58:15]Cloud_ling[/120.221.106.136:24719] logged in with entity id 52392 at (2796.322004013992, 67.5, 1376.5369721918014)
[12:58:15]Cloud_ling joined the game
[12:58:24]<Cloud_ling> 开摆
[12:58:44]Cloud_ling lost connection: Disconnected
[12:58:44]Cloud_ling left the game
[13:31:19]/149.102.143.151:45984 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[13:38:59]/149.102.143.151:35248 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[13:42:12]/149.102.143.151:57994 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[13:48:34]/149.102.143.151:39980 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[13:52:59]/149.102.143.151:36108 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[14:00:07]/149.102.143.151:57020 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[14:06:10]/149.102.143.151:37230 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[14:10:55]/149.102.143.151:40708 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[14:20:53]/149.102.143.151:43080 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[14:32:55]/149.102.143.151:55498 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[14:42:01]/149.102.143.151:44448 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[15:03:20]/149.102.143.151:51954 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[15:08:57]/149.102.143.151:43380 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[15:27:00]/149.102.143.151:47136 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[15:32:21]/149.102.143.151:59044 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[15:38:21]/149.102.143.151:51712 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[15:42:37]com.mojang.authlib.GameProfile@7013f43c[id=<null>,name=Cloud_ling,properties={},legacy=false] (/120.221.106.136:12478) lost connection: Disconnected
[15:42:53]com.mojang.authlib.GameProfile@6f21e117[id=<null>,name=Cloud_ling,properties={},legacy=false] (/120.221.106.136:13847) lost connection: Disconnected
[15:43:32]com.mojang.authlib.GameProfile@4c9f2836[id=<null>,name=Cloud_ling,properties={},legacy=false] (/120.221.106.136:17308) lost connection: Disconnected
[15:43:45]com.mojang.authlib.GameProfile@1bb9442[id=<null>,name=Cloud_ling,properties={},legacy=false] (/120.221.106.136:19473) lost connection: Disconnected
[15:44:02]com.mojang.authlib.GameProfile@194303ac[id=<null>,name=Cloud_ling,properties={},legacy=false] (/120.221.106.136:21241) lost connection: Disconnected
[15:44:22]com.mojang.authlib.GameProfile@52bbc386[id=<null>,name=Cloud_ling,properties={},legacy=false] (/120.221.106.136:22348) lost connection: Disconnected
[15:48:55]/149.102.143.151:47446 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[15:56:38]/149.102.143.151:46134 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[16:03:40]/149.102.143.151:38826 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[16:05:46]/149.102.143.151:35936 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[16:10:13]/149.102.143.151:53538 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[16:16:51]/149.102.143.151:41214 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[16:45:57]/149.102.143.151:49830 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[16:48:01]/149.102.143.151:41746 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[16:52:36]/149.102.143.151:45830 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[17:00:23]/149.102.143.151:37798 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[17:01:30]com.mojang.authlib.GameProfile@860865[id=<null>,name=Cloud_ling,properties={},legacy=false] (/120.221.106.136:56092) lost connection: Disconnected
[17:06:29]/149.102.143.151:39832 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[17:11:17]Cloud_ling[/120.221.106.136:53571] logged in with entity id 52891 at (2816.02839538671, 64.0625, 1377.9801159541246)
[17:11:17]Cloud_ling joined the game
[17:21:10]Cloud_ling lost connection: Disconnected
[17:21:10]Cloud_ling left the game
[17:21:12]Cloud_ling[/120.221.106.136:53749] logged in with entity id 55834 at (2781.443937871641, 74.0, 1420.1522045358638)
[17:21:12]Cloud_ling joined the game
[17:26:01]/149.102.143.151:43708 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[17:30:49]/149.102.143.151:53762 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[17:30:52]Cloud_ling lost connection: Disconnected
[17:30:52]Cloud_ling left the game
[17:31:15]Cloud_ling[/120.221.106.136:57194] logged in with entity id 58412 at (2808.4641280382334, 65.0, 1430.3417824818666)
[17:31:15]Cloud_ling joined the game
[17:34:49]/149.102.143.151:41108 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[17:37:20]/149.102.143.151:50990 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[17:40:26]Cloud_ling lost connection: Disconnected
[17:40:26]Cloud_ling left the game
[17:45:14]/149.102.143.151:57534 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[17:52:39]/149.102.143.151:58000 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[18:16:57]/149.102.143.151:34702 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[18:19:34]/149.102.143.151:41762 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[18:28:58]/149.102.143.151:35588 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[18:42:33]hereiszd[/123.232.191.72:54206] logged in with entity id 60646 at (-725.0464110911931, 96.0, -885.9578246392696)
[18:42:33]hereiszd joined the game
[18:42:45]Cloud_ling[/120.221.106.136:50820] logged in with entity id 60813 at (2806.437771897903, 75.0, 1413.2461786249703)
[18:42:45]Cloud_ling joined the game
[18:42:59]<Cloud_ling> orz
[18:43:01]Cloud_ling lost connection: Disconnected
[18:43:01]Cloud_ling left the game
[18:43:28]<hereiszd> orz
[18:44:10]<hereiszd> !!qb
[18:44:18]<hereiszd> !!qb make 我来炸服
[18:44:18]Automatic saving is now disabled
[18:44:18]Saving the game (this may take a moment!)
[18:44:19]ThreadedAnvilChunkStorage (world): All chunks are saved
[18:44:19]ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[18:44:19]ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[18:44:19]Saved the game
[18:44:26]Automatic saving is now enabled
[18:44:40] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2326ms or 46 ticks behind
[18:45:24]/149.102.143.151:51480 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[18:52:01]/149.102.143.151:32928 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
Caused by: java.lang.StackOverflowError
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
[18:59:09]/149.102.143.151:56822 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[19:00:46]Cloud_ling[/120.221.106.136:61119] logged in with entity id 68891 at (2795.2277228120142, 75.0, 1385.1400603970403)
[19:00:46]Cloud_ling joined the game
Caused by: java.lang.StackOverflowError
[19:01:02]<hereiszd> 寄
[19:01:05]<Cloud_ling> a?
[19:01:10]<hereiszd> 切门失败了
[19:01:13]<Cloud_ling> 草
[19:01:26]<Cloud_ling> 没切过(
[19:01:40]<Cloud_ling> 酶切过(雾
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
[19:03:20]/149.102.143.151:43460 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[19:03:21]<hereiszd> 来点黑曜石（
[19:03:33]<Cloud_ling> a?
[19:03:39]<hereiszd> !!here
[19:03:43]<Cloud_ling> 在工地
[19:03:44]<Cloud_ling> 悲
[19:03:49]<Cloud_ling> !!here
[19:03:52]<hereiszd> 草
[19:04:58]<hereiszd> 你先别急
[19:05:05]<hereiszd> 我不保证不会档（）
[19:05:11]<Cloud_ling> 草
[19:05:25]<Cloud_ling> 去创造档摸一会(
[19:05:26]Cloud_ling lost connection: Disconnected
[19:05:26]Cloud_ling left the game
Caused by: java.lang.StackOverflowError
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
[19:08:38]venti lost connection: Killed
[19:08:38]venti left the game
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
[19:13:35]/149.102.143.151:49964 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.class_129$class_130.<init>(class_129.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[server-intermediary.jar:?]
[19:19:40]/149.102.143.151:35264 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[19:21:27]<hereiszd> !!qb
[19:21:29]<hereiszd> !!qb back
[19:21:33]<hereiszd> !!qb confirm
[19:21:34]hereiszd lost connection: Disconnected
[19:21:34]hereiszd left the game
[19:21:42]ThreadedAnvilChunkStorage (world): All chunks are saved
[19:21:42]ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[19:21:42]ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[19:21:42]ThreadedAnvilChunkStorage (world): All chunks are saved
[19:21:42]ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[19:21:43]ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[19:23:07] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.14.10
[19:23:20] [Worker-Main-12/INFO]: Loaded 927 advancements
[19:23:24]Time elapsed: 2050 ms
[19:23:24]Done (2.430s)! For help, type "help"
[19:29:13]Cloud_ling[/120.221.106.136:37043] logged in with entity id 395 at (2795.2277228120142, 75.0, 1385.1400603970403)
[19:29:13]Cloud_ling joined the game
[19:29:24]Cloud_ling lost connection: Disconnected
[19:29:24]Cloud_ling left the game
[19:34:58]/149.102.143.151:57272 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[19:44:38]/149.102.143.151:48930 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[19:48:04]/149.102.143.151:57726 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[19:56:58]/149.102.143.151:40676 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[20:00:25]/149.102.143.151:43300 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[20:08:05]/149.102.143.151:57722 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[20:11:00]/120.221.106.136:52583 lost connection: Failed to verify username!
[20:29:21]/149.102.143.151:60990 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[20:33:50]/149.102.143.151:47258 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[20:39:02]/149.102.143.151:52342 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[20:45:07]/149.102.143.151:54154 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[22:12:33]/149.102.143.151:35734 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[22:17:40]/149.102.143.151:55714 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[22:23:10]/149.102.143.151:42614 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[22:30:36]/149.102.143.151:47722 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[22:40:36]/149.102.143.151:51686 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[22:49:22]/149.102.143.151:40544 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[22:58:52]/149.102.143.151:55308 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[23:04:33]/149.102.143.151:39150 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[23:11:02]/149.102.143.151:58892 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[23:19:02]/149.102.143.151:49550 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[23:25:19]/149.102.143.151:55934 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[23:38:07]/149.102.143.151:59462 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[23:48:04]/149.102.143.151:59134 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
[23:59:43]/149.102.143.151:44268 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 17 bytes extra whilst reading packet 0
```
