# 2023年05月19日
### 总结
今天系统记录了多起因数据包异常导致的连接丢失事件。具体来说，日志显示在三个不同时间点，三台不同的服务器因为处理数据包时遇到异常而断开了连接。

### 亮点
1. **系统稳定性测试**：连续发生的数据包处理异常可能是对系统稳定性的测试，提示开发者关注系统的异常处理能力。
2. **问题排查线索**：详细的异常信息提供了排查问题的线索，有助于快速定位和修复问题。
3. **安全监控提升**：此类异常的记录对于网络安全监控来说是一个重要指标，有助于及时发现潜在的安全威胁。
```
[00:29:54]/109.123.240.84:47954 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 1 bytes extra whilst reading packet 0
[00:57:22]/109.123.240.84:40726 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2915) was larger than I expected, found 1 bytes extra whilst reading packet 0
[23:21:05]/95.111.247.42:43816 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)
```
